all		:
	cd ComLib;		make all
	cd DiskQ;		make all
	cd SEED_32bit;	make all

install	:
	cd ComLib;		make install
	cd DiskQ;		make install
	cd SEED_32bit;	make install

clean	:
	cd ComLib;		make clean
	cd DiskQ;		make clean
	cd SEED_32bit;	make clean
